allure description
TinkoffCreditSystems/overhave pull request #105
Opened 2021-06-29 09:34 UTC by levananekov

2021-06-29 14:05 UTC, livestreamx requested changes
Тесты просто скопированы, а надо параметризовать

2021-06-30 08:05 UTC, livestreamx commented on tests/unit/testing/conftest.py
> +def test_description_html_manager_settings(
rename

2021-06-30 08:05 UTC, livestreamx commented on tests/unit/testing/conftest.py
> +    if not enable_html:
if enable

2021-06-30 11:28 UTC, artamaney submitted a review, later dismissed

2021-06-30 12:03 UTC, livestreamx commented on makefile
> +	$(VENV)/bin/poetry run pytest -n auto --cov=$(CODE) --cov-fail-under=$(MIN_COVERAGE) --cov-report=html
зачем?

2021-06-30 12:03 UTC, livestreamx commented on tests/unit/testing/conftest.py
> +def test_description_manager_settings(test_blocks_delimiter: str, enable_html) -> OverhaveDescriptionManagerSettings:
bool type

2021-06-30 12:03 UTC, livestreamx commented on tests/unit/testing/conftest.py
> +def test_description_manager(test_description_manager_settings,) -> DescriptionManager:
type

2021-06-30 16:14 UTC, levananekov commented on makefile
> +	$(VENV)/bin/poetry run pytest -n auto --cov=$(CODE) --cov-fail-under=$(MIN_COVERAGE) --cov-report=html
ну чтоб было, все равно на это опираемся когда тесты гоняем локально. Удалю ок

2021-07-01 08:04 UTC, livestreamx approved these changes

2021-07-01 08:23 UTC, merged