first commit of gitlab api bla-bla-bla, without destroying dublication
TinkoffCreditSystems/overhave pull request #94
Opened 2021-05-24 10:04 UTC by artamaney

2021-06-06 12:22 UTC, livestreamx commented on overhave/publication/gitlab/gitlab_publisher.py
> +    """ Class for feature version's merge requests management relative to Atlassian Gitlab API. """
это не Atlassian)

2021-06-06 12:24 UTC, livestreamx commented on overhave/publication/gitlab/gitlab_publisher.py
> +    def _save_as_duplicate(self, context: PublisherContext) -> None:
Перенести в BaseVersionPublisher, удалить отсюда и из StashVersionPublisher

2021-06-06 12:36 UTC, livestreamx commented on overhave/transport/http/gitlab_client/models.py
> +class GitlabRepository(BaseModel):
Ставлю под сомнение актуальность всех моделей. Бегло сравнил. Скопированные поля из Stash-моделей не соответствуют действительности для GitLab. Проверить соответствие каждого поля строго по документации.

2021-06-06 12:39 UTC, livestreamx commented on overhave/transport/http/gitlab_client/settings.py
> +    mr_path: str = "/api/v4/projects/{repository_id}/merge_requests"
некорректный url

2021-06-06 12:42 UTC, livestreamx commented on tests/unit/transport/http/gitlab/test_gitlab_models.py
> +        GitlabMrCreationResponse.parse_obj(
Во первых, тест ничто не проверяет. Давай проверим те поля, которые хотим получить.
Во вторых, давай примеры из оф документации брать.

2021-06-06 12:43 UTC, livestreamx commented on overhave/transport/http/gitlab_client/client.py
> +class GitlabHttpClient(BaseHttpClient[OverhaveGitlabClientSettings]):
Расширить клиент методами Get MR и Update MR согласно документации.
Для возможности как получения удаленных данных, так и их обновления.

2021-06-06 12:53 UTC, livestreamx commented on overhave/publication/gitlab/gitlab_publisher.py
> +class GitlabVersionPublisher(GitVersionPublisher):
Доработать этот паблишер с учетом внедренных в хттп-клиент метода Update.
Реализуем логику:

1. Делаем запрос Create MR.
2. Если перехватываем ошибку дубликации, то делаем Update MR.

Важно: надо проверить, будет ли обновляться PR если просто делать Create MR, тк возможно будет возвращаться ошибка дубликации, но при этом данные будут обновляться (так например работает в Stash).

2021-06-16 04:35 UTC, livestreamx commented on demo/settings.py
> +            client_settings=OverhaveGitlabClientSettings(
Для демо нужна развилка для выбора StashManager либо GitLabManager

2021-06-16 04:39 UTC, livestreamx commented on overhave/publication/git_publisher.py
> +    def _save_as_duplicate(self, context: PublisherContext) -> None:
Вот это же должно быть в BaseVersionPublisher?

2021-06-16 04:43 UTC, livestreamx commented on overhave/transport/http/gitlab_client/models.py
> +    id: str = Field(..., alias="id")
ммм хуета

2021-06-16 04:44 UTC, livestreamx commented on overhave/transport/http/gitlab_client/models.py
> +    source_branch: GitlabBranch = Field(..., alias="fromRef")
пиздеж

2021-06-16 04:47 UTC, livestreamx commented on tests/unit/transport/http/gitlab/test_gitlab_models.py
> +        assert response.web_url == "http://gitlab.example.com/my-group/my-project/merge_requests/1"
проверить все поля, которые у нас присутствуют в модельке

2021-06-16 06:18 UTC, artamaney commented on overhave/publication/git_publisher.py
> +    def _save_as_duplicate(self, context: PublisherContext) -> None:
вообще эта хуйня из stash_publisher.
и чтобы не делать ctrl+c ctrl+v в гитлаб, я решил добавить этот метод в класс, от которого у нас и гитлаб, и стэш наследуется.

гит_паблишер, а не бэйс_вершн_паблишер, потому что метод использует хуевину из гит_вершн_паблишер.
если перенести этот метод в бэйс_вершн_паблишер, то у нас получится, что бэйс импортит гит, и гит импортит бэйс -- говно

хуевина -- NullablePullRequestUrlError

2021-06-16 12:59 UTC, artamaney commented on demo/settings.py
> +        if admin_factory.context.project_settings.publication_manager_type == "gitlab":
ENUM

2021-06-16 13:01 UTC, artamaney commented on demo/settings.py
> +        if admin_factory.context.project_settings.publication_manager_type == "gitlab":
Говнокод.

2021-06-17 04:30 UTC, livestreamx commented on demo/settings.py
> +        admin_factory = get_admin_factory()
вместо этого лучше явно создай объект OverhaveProjectSettings() и с ним уже работай

2021-06-17 04:31 UTC, livestreamx commented on overhave/factory/components/publication_factory.py
> +        if self.context.project_settings.publication_manager_type == "gitlab":
enum

2021-06-17 04:31 UTC, livestreamx commented on overhave/factory/components/publication_factory.py
> +        if self.context.project_settings.publication_manager_type == "gitlab":
это что за дичь, если есть publisher??

2021-06-17 04:33 UTC, livestreamx commented on overhave/test_execution/settings.py
> +class PublicationManagerType(str, enum.Enum):
перенести в overhave/publication/objects.py

2021-06-17 04:43 UTC, artamaney commented on overhave/factory/components/publication_factory.py
> +        if self.context.project_settings.publication_manager_type == "gitlab":
бля.

2021-06-17 06:54 UTC, livestreamx commented on overhave/factory/components/publication_factory.py
> +        if PublicationSettings().publication_manager_type == PublicationManagerType.GITLAB:
if self.context.publication_settings. publication_manager_type

2021-06-17 06:55 UTC, livestreamx commented on overhave/factory/context/publication_context.py
>      ) -> None:
еще PublicationSettings пробросить сюда как publication_settings

2021-06-17 06:55 UTC, livestreamx commented on overhave/transport/http/gitlab_client/models.py
> +    source_branch: str = Field(...)
зачем Field(...)? что это дает?

2021-06-17 10:09 UTC, kataev commented on overhave/factory/components/publication_factory.py
> +        if self.context.publication_settings.publication_manager_type == PublicationManagerType.GITLAB:
add multi mapping maybe?

2021-06-17 10:09 UTC, kataev commented on demo/settings.py
> +        publication_manager_type = PublicationSettings().publication_manager_type
init PublicationSettings for only one prop?

2021-06-17 10:09 UTC, kataev commented on overhave/publication/base_publisher.py
> +            raise RuntimeError
write message

2021-06-17 10:10 UTC, kataev commented on overhave/publication/gitlab/gitlab_publisher.py
> +            logger.exception("Gotten conflict. Try to return last merge-request for Draft with id=%s...", draft_id)
warning?

2021-06-17 10:11 UTC, kataev commented on overhave/publication/gitlab/settings.py
> +                    f"'{feature_type}' reviewers are not specified in " "'feature_type_to_reviewers_mapping' dict!"
string split?
`in " "'f `

2021-06-17 10:11 UTC, livestreamx commented on demo/settings.py
> +        publication_manager_type = PublicationSettings().publication_manager_type
пока так, да

2021-06-17 10:13 UTC, livestreamx commented on overhave/factory/components/publication_factory.py
> +        if self.context.publication_settings.publication_manager_type == PublicationManagerType.GITLAB:
это же настройки, хотим однозначно через env определять, словарь (маппинг) кажется излишним

2021-06-17 10:14 UTC, livestreamx commented on overhave/publication/gitlab/gitlab_publisher.py
> +            logger.exception("Gotten conflict. Try to return last merge-request for Draft with id=%s...", draft_id)
нет

2021-06-17 10:14 UTC, kataev commented on overhave/transport/http/gitlab_client/models.py
> +    def get_mr_url(self) -> str:
`@property?`

2021-06-17 10:14 UTC, kataev commented on overhave/transport/http/gitlab_client/models.py
> +    web_url: Optional[str]
yarl.URL?

2021-06-17 10:15 UTC, kataev commented on overhave/transport/http/gitlab_client/settings.py
> +    def get_mr_url(self, repository_id: str) -> URL:
prop?

2021-06-17 10:18 UTC, kataev commented on overhave/publication/settings.py
> +    publication_manager_type: str = PublicationManagerType.GITLAB
enum?

2021-06-17 10:54 UTC, artamaney commented on overhave/transport/http/gitlab_client/models.py
> +    web_url: Optional[str]
Pydantic не работает с yarl.URL и код завязан на том, что мы дохуя куда передаём ура именно как строку, особенно в пидантик-модели

2021-06-17 10:59 UTC, artamaney commented on overhave/transport/http/gitlab_client/models.py
> +    web_url: Optional[str]
как вариант -- это надо везде переписать, но я бы засунул в рамках другой задачи

2021-06-17 11:50 UTC, livestreamx commented on demo/settings.py
> +        if publication_manager_type == PublicationManagerType.GITLAB:
is ?

2021-06-17 11:57 UTC, livestreamx requested changes

2021-06-17 11:57 UTC, livestreamx commented on demo/settings.py
> +        publication_manager_type = PublicationSettings().publication_manager_type
строка не нужна

2021-06-17 11:57 UTC, livestreamx commented on makefile
> +MIN_COVERAGE ?= 83.88
83.8

2021-06-17 11:57 UTC, livestreamx commented on overhave/factory/components/publication_factory.py
> +        if self.context.publication_settings.publication_manager_type == PublicationManagerType.GITLAB:
is ?

2021-06-17 11:57 UTC, livestreamx commented on overhave/factory/components/publication_factory.py
> +        if isinstance(self.publisher, GitlabVersionPublisher):
хоспади

2021-06-17 12:02 UTC, artamaney commented on overhave/factory/components/publication_factory.py
> +        if self.context.publication_settings.publication_manager_type == PublicationManagerType.GITLAB:
is выдаст False, адреса в памяти у этих объектов разные =(

2021-06-17 12:52 UTC, livestreamx commented on demo/settings.py
> +        if PublicationSettings().publication_manager_type == PublicationManagerType.GITLAB:
IS :aaaaaa:

2021-06-17 12:58 UTC, artamaney commented on demo/settings.py
> +        if PublicationSettings().publication_manager_type == PublicationManagerType.GITLAB:
:aaaaaa:

2021-06-18 07:05 UTC, livestreamx commented on demo/settings.py
> +            repository_id: str = "2034"
нафига если ниже можно сразу передать id?

2021-06-18 07:05 UTC, livestreamx commented on demo/settings.py
> +            settings["publisher_settings"] = OverhaveGitlabPublisherSettings(repository_id=repository_id)
давай через update делать, плюс использовать не строки, а подготовить словарь заранее
а потом им апдейтить settings

2021-06-21 13:02 UTC, livestreamx approved these changes

2021-06-21 13:02 UTC, merged